version: "3.1"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - 5423:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
